### ISSUE TITLE
Possible to make the app available outside of the french app store?

### ISSUE THREAD

**Issue by thomasgentilhomme** [coldiary/AndroTrack#16]
Hi!
I used to have the app on my iphone in canada through the flight test program but now it is not available anymore and it seems the app is only available on the french app store. It would be really nice if you could enable it in canada or even worldwide since it's such a great tool to have!
Thank you!

**Comment by coldiary** [comment]
That's a very late answer but since someone brought up the same request. I'll check to make it available to other countries as well.
