### ISSUE TITLE
Loss of history input

### ISSUE THREAD

**Issue by KeThang-V** [coldiary/AndroTrack#2]
(fr)
Un bug rencontré une fois, à reproduire pour valider le problème.
Étapes de reproduction :
- Ajouter d'un port (port puis retrait) dans l'historique (exemple : 7h30 - 9h00)
- Commencer un nouveau port sans le terminer (exemple : 9h30 - ...)
- Modifier l'heure du début du port en cours pour qu'il coïncide avec l'heure de fin du premier port (exemple : 7h30 - 9h00 ; 9h00 - ...)
Le premier port devrait disparaitre si le bug est réellement existant.

(en)
A bug encountered once, to be reproduced to validate the problem.
Steps to reproduce:
- Add a wearing in the history (wear then remove) (example: 7:30 - 9:00)
- Start a new wearing without finishing it (example: 9:30 am - ...)
- Change the start time of the current wearing to coincide with the end time of the first wearing (example: 7:30 - 9:00; 9:00 - ...)
The first wearing history should disappear if the bug really exists.

**Comment by coldiary** [comment]
Thanks for reporting it !
Got it reproduced.

That storage design of using HealthKit Store as Single Source of Truth  brings a lot of constraints ...
Record consist only of a start and an end. To seek the target record to edit, I do a search for a record from original start date in history. It may give unexpected result if it matches an end date instead.

Best solution would be to implement proper storage of the app's data and keep HealthKitStore in sync.
But I may get around this by filling HKRecord's metadata with an ID, but I'm not sure if we can query that, it's possible to filter out the wrong results to target the one needed.

I'll post update if I have time to address it.
